### ISSUE TITLE
Google collaboratoryで04ab_retinanet_arthropods.ipynbを実行するとエラーがでます

### ISSUE THREAD

**Issue by taro-kuroda-5228** [takumiohym/practical-ml-vision-book-ja#12]
`!pip install tf-models-official==2.9.2`
を実行しようとするとエラーが出ます。

エラーコードを見ると、tf-models-official のインストール時に pyyaml の特定のバージョン（>=5.1,<6.0）が必要とされていますが、それをビルドする際に問題が発生しているようでした。

試したこととしては、以下のコードでpyyamlのバージョンを指定しましたが、うまく行きませんでした。
`!pip install 'pyyaml>=5.1,<6.0'`

また以下のコードでpyyamlの代わりにruamel.yamlを使用することを試してみましたが、同様にうまく行きませんでした。
`!pip install ruamel.yaml`
`import sys`
`import ruamel.yaml`
`sys.modules['pyyaml'] = ruamel.yaml`

お手数ですが、解説法をご教授頂けると幸いです。

エラー全文を以下に掲載します。

Collecting pyyaml<6.0,>=5.1 (from tf-models-official==2.9.2)
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by takumiohym** [comment]
@taro-kuroda-5228 
Issueのお知らせありがとうございます。
こちら、現在`tf-models-official`の方で発生中の問題のようです。
https://discuss.tensorflow.org/t/error-in-pyyaml-installation/18369

`pyyaml`のバージョンを以下で指定することで回避可能なようです。
`!pip install --user pyyaml==5.3.1` 

こちらのcommitで対応しましたので、再度読み込みの上ご確認ください。
https://github.com/takumiohym/practical-ml-vision-book-ja/commit/806671b17c212ac5e6e9069ea17fb313d56221e0
