### ISSUE TITLE
Ch2　gcsの公開ディレクトリアクセスについて

### ISSUE THREAD

**Issue by 77maco** [takumiohym/practical-ml-vision-book-ja#13]
2章にある下記を実行すると
!gsutil cat gs://practical-ml-vision-book/flowers_5_jpeg/flower_photos/train_set.csv | head -20
AccessDeniedException: 403　Permission 'storage.objects.list' denied on resourceと出てアクセスできません。公開bucketなので問題なくアクセスできると思ったのですが、なにか事前に設定が必要でしょうか？export GOOGLE_APPLICATION_CREDENTIALS=***.json（サービスアカウント）を設定してアクセスしましたが、だめでした。

**Comment by takumiohym** [comment]
@77maco 
問題の報告ありがとうございます。原著者側のこちらのバケットが現在アクセスできない状態になっていることが問題のようです。
一旦、`gs://asl-public/practical-ml-vision-book` 以下の同パスにファイルを移しましたので、`asl-public` を追加してご確認いただけますか？

**Comment by 77maco** [comment]
早々の対応ありがとうございます。内容を確認できました。

**Comment by takumiohym** [comment]
ありがとうございます。
こちらのPRで他ファイルも含めて一時的にファイルパス変更いたしました。
https://github.com/takumiohym/practical-ml-vision-book-ja/pull/14

**Comment by takumiohym** [comment]
元GCSバケットがアクセス可能になりましたので、パスをrevertしました。お知らせありがとうございました！
https://github.com/takumiohym/practical-ml-vision-book-ja/commit/d2eef99ea07bd168f8240f696cf98bff3b55957b
