### ISSUE TITLE
ファイルのパスが修復されていものがあります。

### ISSUE THREAD

**Issue by 77maco** [takumiohym/practical-ml-vision-book-ja#15]
たびたびすいません。03b_finetune_MOBILENETV2_flowers5.ipynbの
GCS_DS_PATH = "gs://one-hundred-flowers-public"
だと、permission　deniedになり、下記にすると動作しました。
GCS_DS_PATH = "gs://asl-public/one-hundred-flowers-public"

gs関連のパスは確認された方がよさそうです。

**Comment by takumiohym** [comment]
`GCS_DS_PATH` は `"gs://practical-ml-vision-book/flowers_5_tfr"`となっているはずですが、こちらのファイルであっていますか？

https://github.com/takumiohym/practical-ml-vision-book-ja/blob/main/03_image_models/03b_finetune_MOBILENETV2_flowers5.ipynb

**Comment by 77maco** [comment]
レスポンスが悪く申し訳けありません。ファイルを間違えてました。以下です。４セルめの設定のところです。
03b_finetune_experiment_lr_decay_xception_flowers104.ipynb

**Comment by takumiohym** [comment]
ありがとうございます。
おっしゃるとおり、2ファイルのみに古いパスが残ってしまっていたようでした。
他のノートブックと同様`gs://practical-ml-vision-book/flowers_104_tfr`に変更していただくと動作します。

こちらで変更対応いたしました。
https://github.com/takumiohym/practical-ml-vision-book-ja/pull/16/commits/d0d8e7fa1d5dead0804bac31323d906eff8f148d
